### ISSUE TITLE
Why not mono-repo ?

### ISSUE THREAD

**Issue by blenessy** [containers/libkrun#122]
Hi!

Just want to raise an open question to understand why you chose to distribute qboot, initrd, libkrun.so, and libkrunfw.so over the following three repositories as they are tightly dependent:

* https://github.com/containers/libkrunfw
* https://github.com/containers/libkrun
* https://github.com/slp/qboot

From my point of view it only has disadvantages over maintaining everything in one repo:

- additional build complexity
- more administration
- harder to follow (understand where code comes from)
- binary blobs in libkrunfw

I'm probably missing some key point, which outweighs the disadvantages above ?

**Comment by slp** [comment]
IMHO in many aspects the mono-repo vs. multi-repo question is a matter of tastes more than anything else.

In this particular case, I don't think putting libkrunfw and libkrun would be a good idea because, even though they are co-dependent, they're are also very different projects in nature and their build systems barely have anything in common and, as a consequence, distro packaging will become significantly harder.

On the other hand, putting things such as qboot and initrd-krunfw inside libkrunfw could be a good idea. I'd say it's something to consider doing in the near future.

**Comment by blenessy** [comment]
> On the other hand, putting things such as qboot and initrd-krunfw inside libkrunfw could be a good idea. I'd say it's something to consider doing in the near future.

Yeah this makes a lot of sense. Thanks for explaining.
